<<<<<<< HEAD
version: "3"
services:

=======
version: '3'

services:
>>>>>>> 19072020 - Atualização da estrutura do projetos.
    postgres:
        image: viniciusmattosrj/postgres:11
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=webadm
            - POSTGRES_PASSWORD=A123456
        volumes:
            - ./volumes/postgres11:/var/lib/postgresql/data
<<<<<<< HEAD
            - ./dumps/:/var/lib/postgresql/dump
=======
            - ./dumps/:/var/lib/postgresql/dumps
>>>>>>> 19072020 - Atualização da estrutura do projetos.
        networks:
            servicos:
                ipv4_address: 10.11.0.2

    mysql:
        image: viniciusmattosrj/mysql:5.7
        container_name: mysql
        restart: always
        environment:
<<<<<<< HEAD
            - MYSQL_USER=root
            - MYSQL_PASSWORD=A123456
            - MYSQL_DATABASE=root    
            - MYSQL_ROOT_PASSWORD=A123456
            - MYSQL_ROOT_HOST=%
        volumes:
            - ../../projetos/volumes/mysql57novo:/var/lib/mysql
            - ../../projetos/volumes/mysql57conf:/etc/mysql/mysql.conf.d
=======
            - MYSQL_ROOT_PASSWORD=A123456
            - MYSQL_DATABASE=webadm
            - MYSQL_USER=webadm
            - MYSQL_PASSWORD=A123456
            - MYSQL_ROOT_HOST=%
        volumes:
            - ./volumes/mysql57novo:/var/lib/mysql
            - ./volumes/mysql57conf:/etc/mysql/mysql.conf.d
>>>>>>> 19072020 - Atualização da estrutura do projetos.
        networks:
            servicos:
                ipv4_address: 10.11.0.3

<<<<<<< HEAD
    mongo:
        image: viniciusmattosrj/mongo
        container_name: mongo
        restart: always
        volumes:
            - ./volumes/mongo:/data/db
        networks:
            servicos:
                ipv4_address: 10.11.0.4

=======
>>>>>>> 19072020 - Atualização da estrutura do projetos.
    redis:
        image: viniciusmattosrj/redis:3.0
        container_name: redis
        restart: always
        networks:
            servicos:
<<<<<<< HEAD
                ipv4_address: 10.11.0.5    
 
    elastic:
        image: viniciusmattosrj/elasticsearch:7.6
        container_name: elastic
        restart: always
        environment:
            - node.name=es01
            - "ES_JAVA_OPTS=-Xms500M -Xmx1G"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./volumes/elastic:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            servicos:
                ipv4_address: 10.11.0.6           

    # ftp-icd:
    #     image: viniciusmattosrj/ftp
    #     container_name: ftp
    #     restart: always
    #     environment:
    #         PUBLICHOST: 10.11.0.9
    #         FTP_USER_NAME: "webadm"
    #         FTP_USER_PASS: "A123456"
    #         FTP_USER_HOME: "/home"
    #         FTP_USER_UID: 33
    #         FTP_USER_GID: 33
    #     volumes:
    #         - ./volumes/ftpicd:/var/www/html/home
    #     networks:
    #         servicos:
    #             ipv4_address: 10.11.0.8
=======
                ipv4_address: 10.11.0.4

    mongo:
        image: viniciusmattosrj/mongo
        container_name: mongo
        restart: always
        volumes:
            - ./volumes/mongo:/data/db
        networks:
            servicos:
                ipv4_address: 10.11.0.5

    #emulator:
    #    image: viniciusmattosrj/gcloud-pubsub-emulator
    #    container_name: emulador_pubsub
    #    ports:
    #        - '8085:8085'
    #    networks:
    #        servicos:
    #            ipv4_address: 10.11.0.6

    #elastic:
    #    image: viniciusmattosrj/elasticsearch:7.6
    #    container_name: elastic
    #    restart: always
    #    environment:
    #        - node.name=es01
    #        - 'ES_JAVA_OPTS=-Xms500M -Xmx1G'
    #    ulimits:
    #        memlock:
    #            soft: -1
    #            hard: -1
    #    volumes:
    #        - ./volumes/elastic:/usr/share/elasticsearch/data
    #    ports:
    #        - 9200:9200
    #    networks:
    #        servicos:
    #            ipv4_address: 10.11.0.7

    #ftp-icd:
    #    image: stilliard/pure-ftpd:latest
    #    container_name: ftp
    #    restart: always
    #    environment:
    #        PUBLICHOST: 10.11.0.9
    #        FTP_USER_NAME: "webadmce"
    #        FTP_USER_PASS: "A123456"
    #        FTP_USER_HOME: "/home"
    #        FTP_USER_UID: 33
    #        FTP_USER_GID: 33
    #    volumes:
    #        - ./ftp/ftpicd:/home
    #    networks:
    #        servicos:
    #            ipv4_address: 10.11.0.9
>>>>>>> 19072020 - Atualização da estrutura do projetos.

    smtp:
        image: viniciusmattosrj/mailhog
        container_name: mailhog
        restart: always
<<<<<<< HEAD
        ports:
            - 1025:1025
            - 8025:8025                
=======
        #user: root
        ports:
            - 1025:1025
            - 8025:8025
>>>>>>> 19072020 - Atualização da estrutura do projetos.

    # Cliente gráfico para gestão do postgres
    # pgadmin:
    #   image: viniciusmattosrj/pgadmin4
    #   container_name: pgadmin
    #   restart: always
    #   ports:
    #       - "5050:5050"
    #   volumes:
    #       - ./volumes/postgres/config:/pgadmin/config
    #       - ./volumes/postgres/storage:/pgadmin/storage
    #   dependens_on:
    #       - postgres

<<<<<<< HEAD
    # # Cliente gráfico para gestão do Mysql
=======
    # Cliente gráfico para gestão do Mysql
>>>>>>> 19072020 - Atualização da estrutura do projetos.
    # adminer:
    #   image: viniciusmattosrj/adminer
    #   container_name: adminer
    #   restart: always
    #   ports:
    #       - "8080:8080"
    #   depends_on:
    #       - mysql

networks:
<<<<<<< HEAD
  servicos:
    driver: bridge
    ipam:
     config:
       - subnet: 10.11.0.0/24
         gateway: 10.11.0.1
=======
    servicos:
        driver: bridge
        ipam:
            config:
                - subnet: 10.11.0.0/24
                  #gateway: 10.11.0.1
>>>>>>> 19072020 - Atualização da estrutura do projetos.
